# Generated by Django 5.2.7 on 2025-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tag_comment_course_lesson_rating_lessontags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to='application/%Y/%m'),
        ),
    ]
